# Generated by Django 5.1 on 2024-08-29 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_userinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TECH', 'Technology'), ('HEALTH', 'Health'), ('LIFESTYLE', 'Lifestyle'), ('BUSINESS', 'Business'), ('TRAVEL', 'Travel'), ('EDUCATION', 'Education'), ('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('SPORTS', 'Sports'), ('FINANCE', 'Finance'), ('ART', 'Art'), ('MUSIC', 'Music'), ('GAMING', 'Gaming'), ('POLITICS', 'Politics'), ('SCIENCE', 'Science'), ('BOOKS', 'Books'), ('PHOTOGRAPHY', 'Photography')], max_length=30, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='posts.category')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
