# Generated by Django 5.1 on 2024-08-29 10:34

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', message='Username must contain only letters or numbers and underscores.'), django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('password', models.CharField(max_length=20, validators=[users.models.UserInfo.validate_password_strength])),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
