# Generated by Django 5.1 on 2024-08-29 13:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=256, validators=[users.models.UserInfo.validate_password_strength]),
        ),
    ]
